# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function to calculate kappa score between two terms
#' @param t1_genes, vector containing term1's geneIDs
#' @param t2_genes, vector containing term2's geneIDs
#' @param totalGeneCount, double representing count of all unique genes in dataset of interest
#' @return kappaScore, double
#' @name getKappa
NULL

#' Create a Kappa similarity matrix
#'
#' This function computes kappa scores between pairs of biological terms
#' based on shared gene IDs and creates data frames for analysis in R.
#'
#' @param myTerms, A character vector (R) containing biological terms
#' @param myGenes, A character vector (R) where each item is a string of comma-separated geneIDs corresponding to a single term
#' @param myPvalues, A numeric vector (R) containing p-values corresponding to each term.
#' @param kappaCutoff, Numeric value specifying the cutoff threshold for kappa scores. Default is 0.5.
#' @return A list containing data frames for significant term indices, all kappa scores, and the kappa score matrix.
#'
#' @export
KappaSimilarityMatrix <- function(myTerms, myGenes, myPvalues, kappaCutoff = 0.5) {
    .Call('_RichStudio_KappaSimilarityMatrix', PACKAGE = 'RichStudio', myTerms, myGenes, myPvalues, kappaCutoff)
}

rcpp_hello <- function() {
    .Call('_RichStudio_rcpp_hello', PACKAGE = 'RichStudio')
}

