# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
RcppKappaCluster2 <- function(myTerms, myGenes, myPvalues, kappaCutoff = 0.5) {
    .Call('_RichStudio_RcppKappaCluster2', PACKAGE = 'RichStudio', myTerms, myGenes, myPvalues, kappaCutoff)
}

rcpp_hello <- function() {
    .Call('_RichStudio_rcpp_hello', PACKAGE = 'RichStudio')
}

